---
os: osx
osx_image: xcode12.2
language: minimal
cache: cocoapods
env: WORKSPACE=GEOSwiftMapboxGL.xcworkspace
     SCHEME=GEOSwiftMapboxGL
     SDK=iphonesimulator14.2
     DESTINATION="platform=iOS Simulator,OS=14.2,name=iPhone 11"
before_install:
  - brew upgrade swiftlint
  - gem install xcpretty cocoapods
  - pod repo update
  - pod install

script:
  - set -o pipefail
  - xcodebuild
    -workspace "$WORKSPACE"
    -scheme "$SCHEME"
    -sdk "$SDK"
    -destination "$DESTINATION"
    -configuration Debug
    ONLY_ACTIVE_ARCH=YES
    clean test | xcpretty -c;

after_success:
  - bash <(curl -s https://codecov.io/bash) -J '^GEOSwiftMapboxGL$';
