language: objective-c

before_install:
  - gem install xcpretty
  - gem install cocoapods -v '1.5.0'
  - pod repo update

osx_image: xcode9

cache: cocoapods

env:
  global:
    - WORKSPACE=GEOSwiftMapboxGL.xcworkspace
    - SCHEME=GEOSwiftMapboxGL
    - SDK=iphonesimulator11.0
  matrix:
    # - DESTINATION="OS=10.3,name=iPhone 6"
    - DESTINATION="OS=11.0,name=iPhone 6"
    # - DESTINATION="OS=8.3,name=iPhone 6"

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  - xcodebuild
    -workspace "$WORKSPACE"
    -scheme "$SCHEME"
    -sdk "$SDK"
    -destination "$DESTINATION"
    -configuration Debug
    ONLY_ACTIVE_ARCH=YES
    clean test | xcpretty -c;

  - xcodebuild
    -workspace "$WORKSPACE"
    -scheme "$SCHEME"
    -sdk "$SDK"
    -destination "$DESTINATION"
    -configuration Release
    ONLY_ACTIVE_ARCH=YES
    ENABLE_TESTABILITY=YES
    clean test | xcpretty -c;
