---
os: osx
osx_image: xcode12.3
language: shell
cache: cocoapods

before_install:
  - brew upgrade swiftlint
  - gem install xcpretty cocoapods
  - echo "machine api.mapbox.com
      login mapbox
      password $MAPBOX_SDK_REGISTRY_TOKEN" > ~/.netrc
  - pod repo update
  - pod install

script:
  - set -o pipefail
  - swiftlint
  - xcodebuild
    -workspace GEOSwiftMapboxGL.xcworkspace
    -scheme GEOSwiftMapboxGL
    -sdk iphonesimulator14.3
    -destination "platform=iOS Simulator,OS=14.3,name=iPhone 11"
    -configuration Debug
    ONLY_ACTIVE_ARCH=YES
    clean test | xcpretty -c;

after_success:
  - bash <(curl -s https://codecov.io/bash) -J '^GEOSwiftMapboxGL$';
