---
os: osx
osx_image: xcode11.3
language: minimal
cache: cocoapods
env: WORKSPACE=GEOSwiftMapboxGL.xcworkspace
     SCHEME=GEOSwiftMapboxGL
     SDK=iphonesimulator13.2
     DESTINATION="platform=iOS Simulator,OS=13.3,name=iPhone 11"
before_install:
  - brew upgrade swiftlint
  - gem install xcpretty cocoapods
  - pod repo update
  - pod install

script:
  - xcodebuild
    -workspace "$WORKSPACE"
    -scheme "$SCHEME"
    -sdk "$SDK"
    -destination "$DESTINATION"
    -configuration Debug
    ONLY_ACTIVE_ARCH=YES
    clean test | xcpretty -c;

after_success:
  - bash <(curl -s https://codecov.io/bash) -J '^GEOSwiftMapboxGL$';
